### ISSUE TITLE
You will need to find another name for aur

### ISSUE THREAD

**Issue by Juliaria08** [NNBnh/bfetch#2]
Hi i have an aur account and i first finded the project [bfetch](https://gitlab.com/nautilor/bfetch) and added it to the aur and now in the [r/unixporn subredit](https://www.reddit.com/r/unixporn/comments/ko9my8/oc_bfetch_dynamic_fetching_tool_that_superb/) i found this [bfetch](https://github.com/NNBnh/bfetch) and i dont know what to do. Because im thinking of renaming the other bfetch package to bfetch-gitlab-git and this as bfetch-github-git.

Because of aur things i need to suffix it with git

**Comment by Juliaria08** [comment]
I make the pkg as `bfetch-github-git` and didnt rename the other

**Comment by NNBnh** [comment]
Thanks you so much for porting Bfetch to the AUR.

About the situation, can you name my fetch as `superbfetch`

**Comment by Juliaria08** [comment]
Done changed description and renamed pkg and issued a aur request to merge the other pkg

**Comment by Juliaria08** [comment]
In the aur link is a great idea to put this https://aur.archlinux.org/packages/superbfetch-git/
