### ISSUE TITLE
Can't Install on kubuntu

### ISSUE THREAD

**Issue by NDK2020** [NNBnh/bfetch#3]
I follow these instructions

```
git clone https://github.com/NNBnh/bfetch.git ~/.local/share/bfetch
ln -s ~/.local/share/bfetch/bin/bfetch ~/.local/bin/bfetch
```
the second line has notified:

> ln: failed to create symbolic link '/home/username/.local/bin/bfetch': No such file or directory

System Info:
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.8.0-48-generic
OS Type: 64-bit

Thanks,

**Comment by NNBnh** [comment]
Hello @NDK2020, it's look like your system dosen't have the `~/.local/bin/` directory to symlink `~/.local/share/bfetch/bin/bfetch` into, so let's make that by running this command:
```sh
mkdir -p ~/.local/bin/
```

Also make sure `$HOME/.local/bin` is in `$PATH`. To check it, run:
```sh
echo $PATH
```
if your find `/home/username/.local/bin` then is good to go but if not then please put this line of code:
```sh
export PATH="$PATH:$HOME/.local/bin"
```
into `~/.profile` or `~/bashrc`.

**Comment by NDK2020** [comment]
Hi,
I've installed successfully after following your reply. Bfetch shows initialize page.

I've created a folder as the path is "/home/ndk/.config/bfetch/info" according to the guideline.

> SuperB Fetch looking for and execute $XDG_CONFIG_HOME/bfetch/info for info element as default, you can copy this info template with Fetchutils as a starting point and customizing.

the file "info" is also put in there from  "this info template with Fetchutils"

then I ran command "bfetch" again and got

> bash: OS: command not found

Thanks,

**Comment by NNBnh** [comment]
Have you modified the `info` file, if so can you show me what the file look like?

**Comment by NDK2020** [comment]
Hi,
> Have you modified the `info` file, if so can you show me what the file look like?

I didn't change anything, just copy the content from there 

> https://github.com/NNBnh/textart-collections/blob/main/fetch/info.textart

and put it in the file 'info'.

Thanks,

**Comment by NNBnh** [comment]
Hello @NDK2020, the [`info` file](https://github.com/NNBnh/textart-collections/blob/main/fetch/info.textart) run perfectly fine in our tested machine. I think the problem is on your machine, specifically your `bash` config... please run these codes separately and send back the output:
```sh
lsb_release -sd
```
```sh
OS=$(lsb_release -sd | sed -e 's/"//g')
```
```sh
printf "${OS:-os}"
```
Thanks,

**Comment by NDK2020** [comment]
Hi,
Here are the output
> lsb_release -sd

return "Ubuntu 20.04.2 LTS"

> OS=$(lsb_release -sd | sed -e 's/"//g')
>  printf "${OS:-os}"

return "Ubuntu 20.04.2 LTS"

I restart the machine and type bfetch again then  it provides me a different result.
>  bash: /home/<username>/.config/bfetch/info: Permission denied

Then I temporarily remove the info file and it become normal. Here is the screenshot 
![image](https://user-images.githubusercontent.com/72021635/114645279-56b38380-9d03-11eb-8bc4-47a752ddf851.png)

Thanks,

**Comment by NNBnh** [comment]
Hello @NDK2020, look like the problem is easy to fix than i thought, just make the `info` script executable by running the following command:
```sh
chmod +x ~/.config/bfetch/info
```
Sorry for not making this clear, i should docmented this better.

**Comment by NDK2020** [comment]
Hi.
Sr for bother you that I'm not familiar with bash script.
I've put art and color successfully into my bfetch. Look super cool!

btw, can you post this 'info' template
![image](https://user-images.githubusercontent.com/72021635/115029334-1402ce80-9ef0-11eb-90b0-6754f83f86b1.png)
and how can I put _memory, cpu usage_ into 'info' file 

Thanks,

**Comment by NNBnh** [comment]
@NDK2020  Sure 😉 https://github.com/NNBnh/dots/blob/master/home/.config/bfetch/info, this is the script that i'm currently using.
