### ISSUE TITLE
Missing font from friglet example

### ISSUE THREAD

**Issue by D3vil0per** [NNBnh/bfetch#8]
Hello,
I know it is not a particular issue. I was trying to replicate the same bfetch output in the example video of this repository. When I set the following:
```
export BFETCH_INFO="curl --silent --location 'wttr.in/london?0pq'"                                                                                                   
export BFETCH_ART="printf \"\033[35m\"; figlet -f Bloody Spooky"                                                                                                     
export BFETCH_COLOR="$XDG_DATA_HOME/textart/color/icon/ghosts.textart"                                                                                               bfetch 
```
I get an error related to the Bloody font missing. I tried to download also GB of fonts but I was not able to find it. Do you know how we can retrieve the Bloody font? I'm working on Arch Linux.

Thanks

**Comment by NNBnh** [comment]
The font is from this repo: https://github.com/xero/figlet-fonts#readme

The README.md have a quick manual install guide but I'm not sure how to install it with AUR...

**Comment by D3vil0per** [comment]
> The font is from this repo: https://github.com/xero/figlet-fonts#readme
> 
> The README.md have a quick manual install guide but I'm not sure how to install it with AUR...

Yes. It is. I was not able to find it by googling. No need to make from AUR, I can make a package that takes files directly from that git repository.
