### ISSUE TITLE
Can't run on MacOs

### ISSUE THREAD

**Issue by happyRip** [NNBnh/bfetch#9]
I've tried running the `bfetch` on a M1 MacBook, but it throws an error:

```sh
$ bfetch
script: illegal option -- -
usage: script [-adkpqr] [-t time] [file [command ...]]
script: illegal option -- -
usage: script [-adkpqr] [-t time] [file [command ...]]



```

System information:

```sh
os: macOS 12.4
host: MacBookPro17,1
kernel: 21.5.0
shell: zsh 5.8.1
cpu: Apple M1
```

```sh
$ sh --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

Same outcome for both `curl` and `git` installation.

edit: Updated the title as it seems like the error is with the MacOs in general not M1 hardware

**Comment by NNBnh** [comment]
Hello,

Sorry for the late reply. I'm currently don't have a MacOS device but i'm reaching out to a close friend who have. I'm trying to fix this as soon as possible.

**Comment by happyRip** [comment]
Thanks for looking into this.
In the meantime I've found a topic regarding the issue with `script` on macos [here](https://superuser.com/questions/1530368/install-gnu-script-command-on-mac).

I've swapped `script` for `unbuffer` installed with brew
```
brew install expect
```
And was able to run the `bfetch` that way
<img width="748" alt="image" src="https://user-images.githubusercontent.com/73070465/180960863-bebbff34-a0a3-488c-bad2-95d584e18c46.png">

```diff
--- bfetch	2022-07-26 10:30:43.000000000 +0200
+++ bfetch.new	2022-07-26 10:31:38.000000000 +0200
@@ -179,7 +179,7 @@
 		eval "export BFETCH_${element}_HEIGHT=\$(( TERM_HEIGHT - used_height ))"
 		eval "export BFETCH_${element}_WIDTH=\$(( TERM_WIDTH - used_width ))"

-		eval "TEXTART_$element=\$(script --quiet /dev/null --command \"\$${element}_COMMANDS\")"
+		eval "TEXTART_$element=\$(unbuffer -p \"\$${element}_COMMANDS\")"
 		eval "printf '%s' \"\$TEXTART_$element\" | sed -e 's/\x1B\[[0-9;]*[JKmsu]//g' -e 's/./-/g'" > "$TEMPORARY"

 		height='0'
```
